export interface Contact {
  name: string;
  title: string;
  phone?: string;
  email?: string;
  address?: string;
  category:
    | "animal"
    | "council"
    | "mayor"
    | "county"
    | "state"
    | "federal"
    | "police"
    | "media"
    | "nonprofit";
  note?: string;
}

export const CONTACTS: Contact[] = [

  // ─── Animal & Wildlife Agencies ──────────────────────────────────────────
  {
    name: "Fresno Animal Center",
    title: "City Animal Services — Main Line",
    phone: "(559) 621-5795",
    email: "FCAnimalCenter@fresno.gov",
    address: "7172 N. San Pablo Ave, Fresno, CA 93650",
    category: "animal",
    note: "Primary contact for stray animal reports, field officers, and intake",
  },
  {
    name: "Fresno Animal Center — Field Services",
    title: "Animal Control Field Officers",
    phone: "(559) 621-5795",
    email: "FCAnimalCenter@fresno.gov",
    category: "animal",
    note: "Request field officer dispatch for urgent welfare concerns",
  },
  {
    name: "Fresno County Animal Control",
    title: "County Animal Services (unincorporated areas)",
    phone: "(559) 600-3471",
    email: "AnimalControl@FresnoCountyCA.gov",
    address: "3491 N. Cedar Ave, Fresno, CA 93703",
    category: "animal",
    note: "Handles stray animals in unincorporated Fresno County areas outside city limits",
  },
  {
    name: "Fresno Humane Animal Services",
    title: "Non-Profit Animal Shelter",
    phone: "(559) 233-7722",
    email: "info@fresnohumane.org",
    address: "7700 E. Kings Canyon Rd, Fresno, CA 93727",
    category: "animal",
    note: "Partner shelter; takes owner surrenders and transfers from city shelter",
  },
  {
    name: "Central California SPCA",
    title: "SPCA — Cruelty Investigations",
    phone: "(559) 233-7722",
    email: "info@ccspca.com",
    address: "103 S. Hughes Ave, Fresno, CA 93706",
    category: "animal",
    note: "Investigates animal cruelty; has Peace Officer status in California",
  },
  {
    name: "CA Dept. of Food & Agriculture — Animal Health",
    title: "State Animal Health Branch",
    phone: "(916) 900-5002",
    email: "AHFSS@cdfa.ca.gov",
    address: "1220 N Street, Sacramento, CA 95814",
    category: "animal",
    note: "Escalate if local agencies repeatedly fail to act on documented welfare concerns",
  },
  {
    name: "CA Dept. of Fish & Wildlife — CDFW",
    title: "Wildlife Enforcement",
    phone: "(559) 222-3761",
    email: "cdfwinfo@wildlife.ca.gov",
    category: "animal",
    note: "For wildlife-related concerns; also involved in hoarding cases involving wildlife",
  },
  {
    name: "ASPCA — National Cruelty Hotline",
    title: "American Society for Prevention of Cruelty to Animals",
    phone: "(888) 666-2279",
    email: "investigations@aspca.org",
    category: "animal",
    note: "National resource; can advise and escalate cases with documented evidence",
  },
  {
    name: "Humane Society of the United States",
    title: "HSUS — Animal Cruelty Program",
    phone: "(202) 452-1100",
    email: "info@humanesociety.org",
    category: "animal",
    note: "National advocacy; can intervene in systemic local welfare failures",
  },

  // ─── Fresno Police & Safety ───────────────────────────────────────────────
  {
    name: "Fresno Police — Non-Emergency",
    title: "FPD Non-Emergency Dispatch",
    phone: "(559) 621-7000",
    category: "police",
    note: "For urgent animal welfare situations that do not require 911",
  },
  {
    name: "Fresno Police — Crime Prevention Unit",
    title: "Community Outreach & Animal Cruelty Reports",
    phone: "(559) 621-7000",
    email: "police@fresno.gov",
    category: "police",
    note: "For documented neglect patterns that may involve criminal conduct",
  },
  {
    name: "Fresno County Sheriff — Non-Emergency",
    title: "Fresno County Sheriff's Office",
    phone: "(559) 600-8000",
    email: "sheriff@fresnosheriff.org",
    category: "police",
    note: "Handles law enforcement in unincorporated county areas outside city limits",
  },

  // ─── Fresno Mayor & City Manager ──────────────────────────────────────────
  {
    name: "Mayor Jerry Dyer",
    title: "Mayor, City of Fresno",
    phone: "(559) 621-8000",
    email: "jerry.dyer@fresno.gov",
    address: "2600 Fresno St, Room 2063, Fresno, CA 93721",
    category: "mayor",
    note: "Escalate for repeated agency non-response; include Report ID in all correspondence",
  },
  {
    name: "Mayor's Office — City Manager",
    title: "Office of the City Manager",
    phone: "(559) 621-8000",
    email: "citymanager@fresno.gov",
    category: "mayor",
    note: "Operational escalation for unanswered animal control concerns",
  },
  {
    name: "Fresno City Clerk",
    title: "Official Public Records (CPRA)",
    phone: "(559) 621-7650",
    email: "cityclerk@fresno.gov",
    category: "mayor",
    note: "Submit California Public Records Act requests for animal control response history",
  },

  // ─── Fresno City Council ──────────────────────────────────────────────────
  {
    name: "Council Member Miguel Arias",
    title: "District 1 — Central / Downtown Fresno",
    phone: "(559) 621-8000",
    email: "miguel.arias@fresno.gov",
    category: "council",
    note: "Central Fresno, Downtown, Chinatown, Tower District",
  },
  {
    name: "Council Member Mike Karbassi",
    title: "District 2 — Northwest Fresno",
    phone: "(559) 621-8000",
    email: "mike.karbassi@fresno.gov",
    category: "council",
    note: "Northwest Fresno — verify current rep at fresno.gov",
  },
  {
    name: "Council Member Luis Chavez",
    title: "District 3 — Southeast Fresno",
    phone: "(559) 621-8000",
    email: "luis.chavez@fresno.gov",
    category: "council",
    note: "Southeast and south-central Fresno neighborhoods",
  },
  {
    name: "Council Member Tyler Maxwell",
    title: "District 4 — Northeast Fresno",
    phone: "(559) 621-8000",
    email: "tyler.maxwell@fresno.gov",
    category: "council",
    note: "Northeast Fresno — Fig Garden, Woodward Park area",
  },
  {
    name: "Council Member Annalisa Perea",
    title: "District 5 — West / Central Fresno",
    phone: "(559) 621-8000",
    email: "annalisa.perea@fresno.gov",
    category: "council",
    note: "West and central Fresno",
  },
  {
    name: "Council Member Garry Bredefeld",
    title: "District 6 — North Fresno",
    phone: "(559) 621-8000",
    email: "garry.bredefeld@fresno.gov",
    category: "council",
    note: "North Fresno",
  },
  {
    name: "Council Member Nelson Esparza",
    title: "District 7 — Southwest Fresno",
    phone: "(559) 621-8000",
    email: "nelson.esparza@fresno.gov",
    category: "council",
    note: "Southwest Fresno neighborhoods",
  },

  // ─── Fresno County Board of Supervisors ──────────────────────────────────
  {
    name: "Supervisor Sal Quintero",
    title: "Fresno County — District 1",
    phone: "(559) 600-1801",
    email: "squintero@fresnocountyca.gov",
    address: "2281 Tulare St, Suite 304, Fresno, CA 93721",
    category: "county",
    note: "County District 1 — escalate animal control concerns in unincorporated areas",
  },
  {
    name: "Supervisor Steve Brandau",
    title: "Fresno County — District 2",
    phone: "(559) 600-1802",
    email: "sbrandau@fresnocountyca.gov",
    address: "2281 Tulare St, Suite 304, Fresno, CA 93721",
    category: "county",
    note: "County District 2",
  },
  {
    name: "Supervisor Buddy Mendes",
    title: "Fresno County — District 3",
    phone: "(559) 600-1803",
    email: "bmendes@fresnocountyca.gov",
    address: "2281 Tulare St, Suite 304, Fresno, CA 93721",
    category: "county",
    note: "County District 3",
  },
  {
    name: "Supervisor Brian Pacheco",
    title: "Fresno County — District 4",
    phone: "(559) 600-1804",
    email: "bpacheco@fresnocountyca.gov",
    address: "2281 Tulare St, Suite 304, Fresno, CA 93721",
    category: "county",
    note: "County District 4",
  },
  {
    name: "Supervisor Nathan Magsig",
    title: "Fresno County — District 5",
    phone: "(559) 600-1805",
    email: "nmagsig@fresnocountyca.gov",
    address: "2281 Tulare St, Suite 304, Fresno, CA 93721",
    category: "county",
    note: "County District 5 — mountain/foothill communities",
  },
  {
    name: "Fresno County CEO",
    title: "Fresno County Chief Executive Officer",
    phone: "(559) 600-2600",
    email: "cao@fresnocountyca.gov",
    category: "county",
    note: "County operational escalation for animal control funding and staffing issues",
  },

  // ─── California State Officials ───────────────────────────────────────────
  {
    name: "Governor Gavin Newsom",
    title: "Governor of California",
    phone: "(916) 445-2841",
    email: "governor@gov.ca.gov",
    address: "1303 10th Street, Suite 1173, Sacramento, CA 95814",
    category: "state",
    note: "Last resort escalation for systemic, documented local government failure to act",
  },
  {
    name: "Lt. Governor Eleni Kounalakis",
    title: "Lieutenant Governor of California",
    phone: "(916) 445-8994",
    email: "ltgovernor@ltg.ca.gov",
    category: "state",
    note: "Alternative state-level contact; oversees state boards and commissions",
  },
  {
    name: "CA Attorney General Rob Bonta",
    title: "California Department of Justice",
    phone: "(916) 210-6276",
    email: "info@doj.ca.gov",
    address: "P.O. Box 944255, Sacramento, CA 94244",
    category: "state",
    note: "For documented animal cruelty patterns that constitute criminal conduct (Penal Code 597)",
  },
  {
    name: "State Senator Melissa Hurtado",
    title: "CA Senate District 14 — Fresno / Tulare area",
    phone: "(559) 326-5766",
    email: "senator.hurtado@senate.ca.gov",
    address: "2350 W. Shaw Ave #132, Fresno, CA 93711",
    category: "state",
    note: "State Senate — covers much of Fresno County; animal welfare legislation contact",
  },
  {
    name: "State Senator Anna Caballero",
    title: "CA Senate District 16 — Central Valley",
    phone: "(209) 726-5595",
    email: "senator.caballero@senate.ca.gov",
    category: "state",
    note: "State Senate — Central Valley district covering parts of Fresno area",
  },
  {
    name: "Assemblymember Esmeralda Soria",
    title: "CA Assembly District 27 — Fresno",
    phone: "(559) 445-5532",
    email: "assemblymember.soria@assembly.ca.gov",
    address: "2550 Mariposa Mall, Suite 3008, Fresno, CA 93721",
    category: "state",
    note: "State Assembly — covers central and west Fresno; active on local issues",
  },
  {
    name: "Assemblymember Joaquin Arambula",
    title: "CA Assembly District 31 — Fresno / Kings",
    phone: "(559) 447-4338",
    email: "assemblymember.arambula@assembly.ca.gov",
    address: "5090 N. Fruit Ave, Suite 102, Fresno, CA 93711",
    category: "state",
    note: "State Assembly — covers south and central Fresno",
  },
  {
    name: "Assemblymember Jim Patterson",
    title: "CA Assembly District 8 — North Fresno / Clovis",
    phone: "(559) 447-4350",
    email: "assemblymember.patterson@assembly.ca.gov",
    category: "state",
    note: "State Assembly — covers north Fresno, Clovis, and surrounding areas",
  },
  {
    name: "CA CDFA — Secretary Karen Ross",
    title: "CA Secretary of Food & Agriculture",
    phone: "(916) 654-0433",
    email: "secretary@cdfa.ca.gov",
    address: "1220 N Street, Sacramento, CA 95814",
    category: "state",
    note: "State-level oversight of animal welfare standards and enforcement",
  },

  // ─── Federal ──────────────────────────────────────────────────────────────
  {
    name: "Rep. Jim Costa",
    title: "U.S. Representative — CA-21 (Fresno)",
    phone: "(559) 495-1620",
    email: "costa.house.gov/contact",
    address: "855 M Street, Suite 940, Fresno, CA 93721",
    category: "federal",
    note: "Federal representative — use for cases involving federal animal welfare violations",
  },
  {
    name: "Senator Alex Padilla",
    title: "U.S. Senator — California",
    phone: "(559) 497-5109",
    email: "padilla.senate.gov/contact",
    address: "2500 Tulare St, Suite 5290, Fresno, CA 93721",
    category: "federal",
    note: "U.S. Senate — federal-level escalation",
  },
  {
    name: "Senator Laphonza Butler / Adam Schiff",
    title: "U.S. Senator — California",
    phone: "(202) 224-3553",
    email: "schiff.senate.gov/contact",
    category: "federal",
    note: "Please verify current CA Senator at senate.gov/senators",
  },
  {
    name: "USDA Animal Care (APHIS)",
    title: "Federal Animal Welfare Enforcement",
    phone: "(844) 820-2234",
    email: "ace@usda.gov",
    category: "federal",
    note: "Enforces federal Animal Welfare Act; relevant for commercial operations",
  },

  // ─── Local Media ──────────────────────────────────────────────────────────
  {
    name: "Fresno Bee",
    title: "Local Newspaper — News Tips",
    email: "newstips@fresnobee.com",
    phone: "(559) 441-6111",
    category: "media",
    note: "Largest local newspaper; investigative and local news tips",
  },
  {
    name: "ABC30 (KFSN-TV)",
    title: "ABC Fresno — I-Team Tips",
    email: "abc30tips@abc.com",
    phone: "(559) 222-0300",
    category: "media",
    note: "Strong investigative track record on consumer and public safety",
  },
  {
    name: "FOX26 Fresno (KMPH)",
    title: "FOX26 — News Tips",
    email: "newstips@kmph.com",
    phone: "(559) 255-2600",
    category: "media",
    note: "Local FOX affiliate",
  },
  {
    name: "CBS47 / KSEE24 Fresno",
    title: "CBS / NBC Local News",
    email: "news@cbs47.tv",
    phone: "(559) 650-4747",
    category: "media",
    note: "Combined CBS47 / KSEE24 Fresno newsdesk",
  },
  {
    name: "Univision Fresno (KFTV)",
    title: "Spanish-Language News",
    phone: "(559) 435-0777",
    email: "noticias@univisionfresno.com",
    category: "media",
    note: "Reaches Spanish-speaking communities across the Central Valley",
  },
  {
    name: "GV Wire",
    title: "Online News — Fresno",
    email: "tips@gvwire.com",
    category: "media",
    note: "Digital-first local news covering Fresno government and civic issues",
  },
  {
    name: "The Fresno Free Flyer",
    title: "Community-focused local outlet",
    email: "editor@thefresnofreflyer.com",
    category: "media",
    note: "Community and neighborhood-focused local coverage",
  },

  // ─── Nonprofits & Rescue ──────────────────────────────────────────────────
  {
    name: "Fix Our Ferals",
    title: "Fresno TNR Organization",
    email: "fixourferals@gmail.com",
    category: "nonprofit",
    note: "Trap-Neuter-Return for feral cats in Fresno; community cats resources",
  },
  {
    name: "Fresno Bully Rescue",
    title: "Dog Rescue Organization",
    email: "fresnobullyrescue@gmail.com",
    category: "nonprofit",
    note: "Rescue for stray and abandoned dogs in Fresno area",
  },
  {
    name: "The Paw Project — Fresno",
    title: "Animal Advocacy & Rescue",
    phone: "(559) 499-4278",
    category: "nonprofit",
    note: "Local advocacy and direct rescue assistance",
  },
  {
    name: "Animal Legal Defense Fund",
    title: "Animal Rights Legal Organization",
    phone: "(707) 795-2533",
    email: "info@aldf.org",
    category: "nonprofit",
    note: "Provides legal support for animal cruelty cases; can help when agencies fail",
  },
  {
    name: "National Animal Cruelty Hotline",
    title: "ASPCA 24/7 Hotline",
    phone: "(888) 666-2279",
    category: "nonprofit",
    note: "24/7 national cruelty reporting and guidance hotline",
  },
];

export const CATEGORY_LABELS: Record<Contact["category"], string> = {
  animal: "Animal Services & Agencies",
  council: "Fresno City Council",
  mayor: "Mayor, City Manager & City Clerk",
  county: "Fresno County Officials",
  state: "California State Officials",
  federal: "Federal Officials & Agencies",
  police: "Police & Law Enforcement",
  media: "Local & Regional Media",
  nonprofit: "Nonprofits, Rescue & Legal",
};

export const CATEGORY_COLORS: Record<Contact["category"], string> = {
  animal: "border-primary bg-primary/5",
  council: "border-accent/50 bg-accent/5",
  mayor: "border-destructive/40 bg-destructive/5",
  county: "border-orange-400/40 bg-orange-400/5",
  state: "border-purple-400/40 bg-purple-400/5",
  federal: "border-blue-400/40 bg-blue-400/5",
  police: "border-muted bg-muted/30",
  media: "border-secondary/50 bg-secondary/5",
  nonprofit: "border-green-500/40 bg-green-500/5",
};
