import { useState } from "react";
import {
  FileText, Copy, Printer, Download, CheckCircle2,
  PawPrint, ArrowRight, Inbox,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { KurzgesagtDog } from "@/components/KurzgesagtDog";
import { KurzgesagtCat } from "@/components/KurzgesagtCat";
import { getReports, STATUS_LABELS, type Report } from "@/lib/storage";

function generateReportText(report: Report): string {
  const date = new Date(report.createdAt).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });
  const observed = new Date(report.dateObserved).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  return `
VOICEMAP FRESNO — ANIMAL WELFARE CONCERN REPORT
================================================
Report Generated: ${date}
Report ID: ${report.id}
Status: ${STATUS_LABELS[report.status]}

INCIDENT SUMMARY
----------------
This report documents a submitted animal welfare concern based on direct observation
by a Fresno resident. The following information is presented as a reported concern
and alleged incident requiring review. No legal findings are made herein.

ANIMAL WELFARE CONCERN SUMMARY
-------------------------------
Animal Type: ${report.animalType.charAt(0).toUpperCase() + report.animalType.slice(1)}
Number of Animals: ${report.count}
Immediate Danger Assessed: ${report.inDanger.toUpperCase()}
Concern Type(s): ${report.concernTypes.map((c) => c.replace(/\b\w/g, (l) => l.toUpperCase())).join(", ")}

LOCATION SUMMARY
----------------
Location / Cross Streets: ${report.location}
Neighborhood: ${report.neighborhood}

TIMELINE
--------
Date of Alleged Incident: ${observed}
Time of Alleged Incident: ${report.timeObserved || "Not specified"}
Date Reported via VoiceMap: ${date}

DESCRIPTION OF SUBMITTED EVIDENCE
-----------------------------------
${report.description}

Evidence Notes:
${report.evidenceNotes || "No additional evidence notes provided."}

AGENCIES CONTACTED
------------------
${report.agenciesContacted || "No agencies contacted prior to this report."}

Response Received:
${report.responseReceived || "No response documented at this time."}

RECOMMENDED NEXT STEPS
-----------------------
1. Forward this report to Fresno Animal Center (559) 621-5795
2. If animal is in immediate danger, call Fresno Police Non-Emergency: (559) 621-7000
3. If no response after 48 hours, escalate to City Council
4. Document any changes in the animal's condition with updated submissions

SUGGESTED AGENCY EMAIL — ANIMAL CONTROL
-----------------------------------------
Subject: Submitted Animal Welfare Concern — Requires Review — ${report.neighborhood}

"I am submitting a documented animal welfare concern for your review. I am requesting
an investigation of an alleged incident at ${report.location} in the ${report.neighborhood}
neighborhood. I am asking whether this location has received prior reports. The
concern involves ${report.count} ${report.animalType}(s) observed on ${observed}.
Please advise what action, if any, will be taken. Report ID: ${report.id}."

SUGGESTED CITY COUNCIL EMAIL
------------------------------
Subject: Pattern of Public Reports — Animal Welfare Concern Requiring City Response

"I am a Fresno resident writing to escalate a submitted animal welfare concern that
I believe requires city-level attention. I am requesting review of a documented
pattern of reported concerns in the ${report.neighborhood} area. I am asking whether
the Fresno Animal Center has received prior reports from this location and what
follow-up was completed. Report ID: ${report.id}."

DISCLAIMER
----------
This report was generated by VoiceMap Fresno, a free public-interest documentation
tool. All information is submitted as reported concerns and alleged incidents. This
report does not constitute a legal finding. It does not identify any individual as
responsible for harm. Fresno residents are encouraged to submit only information
based on direct observation and to avoid confrontation, trespassing, or interference
with ongoing investigations.

Report generated via VoiceMap Fresno — voicemap.fresno.app
`.trim();
}

const EMAIL_TEMPLATES = [
  {
    id: "animal-control",
    title: "Animal Control / Police",
    accent: "#028391",
    light: "rgba(2,131,145,0.07)",
    template: (r: Report) =>
      `Subject: Animal Welfare Concern — Requires Review — ${r.neighborhood}\n\nI am submitting a documented animal welfare concern. I am requesting an investigation of an alleged incident at ${r.location}. I am asking whether this location has received repeated reports. Please advise what action, if any, will be taken. Report ID: ${r.id}.`,
  },
  {
    id: "city-council",
    title: "City Council / Mayor",
    accent: "#FAA968",
    light: "rgba(250,169,104,0.08)",
    template: (r: Report) =>
      `Subject: Pattern of Public Reports — Requires City Response — ${r.neighborhood}\n\nI am a Fresno resident escalating a documented concern that requires city-level attention. I am requesting review of submitted evidence regarding an animal welfare pattern in ${r.neighborhood}. I am asking what follow-up has been completed. Report ID: ${r.id}.`,
  },
  {
    id: "media",
    title: "Media Tip",
    accent: "#F85525",
    light: "rgba(248,85,37,0.06)",
    template: (r: Report) =>
      `Media Tip — Animal Welfare Concern, Fresno\n\nI am sharing a documented concern involving stray animals in the ${r.neighborhood} neighborhood of Fresno. Multiple reports have been submitted. Agency response has been limited. I am available to provide further documentation. Report ID: ${r.id}.`,
  },
];

export default function ReportGenerator() {
  const reports = getReports();
  const [selected, setSelected] = useState<Report | null>(null);
  const [copied, setCopied] = useState(false);
  const [copiedTmpl, setCopiedTmpl] = useState<string | null>(null);

  const reportText = selected ? generateReportText(selected) : "";

  function handleCopy() {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleCopyTemplate(id: string, text: string) {
    navigator.clipboard.writeText(text);
    setCopiedTmpl(id);
    setTimeout(() => setCopiedTmpl(null), 2000);
  }

  function handleDownload() {
    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `voicemap-report-${selected?.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="min-h-screen pt-24 pb-16 px-4">
      <div className="max-w-5xl mx-auto">

        {/* ── Page header ── */}
        <div
          className="rounded-3xl px-8 py-6 mb-8 flex items-center gap-6"
          style={{
            background: "rgba(255,252,243,0.92)",
            boxShadow: "0 2px 12px rgba(1,32,78,0.07)",
          }}
        >
          <div className="flex-1 min-w-0">
            <div
              className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold mb-3"
              style={{ background: "rgba(2,131,145,0.12)", color: "#028391" }}
            >
              <FileText size={11} /> Report Generator
            </div>
            <h1 className="font-heading text-3xl font-bold mb-1.5">Generate a Report Packet</h1>
            <p className="text-sm text-muted-foreground max-w-lg leading-relaxed">
              Turn a documented concern into a formal, legally careful report packet ready to
              send to agencies, city officials, and media.
            </p>
          </div>
          <div className="hidden sm:flex items-end gap-2 flex-shrink-0">
            <KurzgesagtCat size={75} />
            <KurzgesagtDog size={65} />
          </div>
        </div>

        <div className="grid lg:grid-cols-5 gap-6">

          {/* ── Left: concern selector ── */}
          <div className="lg:col-span-2 space-y-3">
            <h3 className="font-heading font-bold text-base mb-3 flex items-center gap-2">
              <PawPrint size={15} style={{ color: "#028391" }} />
              Select a Documented Concern
            </h3>

            {reports.length === 0 ? (
              <div
                className="rounded-2xl p-8 text-center"
                style={{
                  background: "rgba(255,252,243,0.88)",
                  boxShadow: "0 2px 12px rgba(1,32,78,0.07)",
                }}
              >
                <Inbox size={28} className="mx-auto mb-3 text-muted-foreground opacity-50" />
                <p className="text-muted-foreground text-sm mb-4">
                  No concerns documented yet.
                </p>
                <a
                  href="/submit"
                  className="inline-flex items-center gap-1.5 text-sm font-semibold rounded-xl px-4 py-2 transition-all"
                  style={{ background: "#028391", color: "white" }}
                >
                  Submit a Concern <ArrowRight size={14} />
                </a>
              </div>
            ) : (
              reports.map((r) => (
                <button
                  key={r.id}
                  data-testid={`button-select-report-${r.id}`}
                  onClick={() => setSelected(r)}
                  className="w-full text-left rounded-2xl p-4 transition-all"
                  style={{
                    background: selected?.id === r.id
                      ? "rgba(2,131,145,0.08)"
                      : "rgba(255,252,243,0.88)",
                    border: selected?.id === r.id
                      ? "2px solid rgba(2,131,145,0.45)"
                      : "2px solid transparent",
                    boxShadow: "0 2px 10px rgba(1,32,78,0.07)",
                  }}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <p className="font-semibold text-sm capitalize">{r.animalType} — {r.location}</p>
                      <p className="text-xs text-muted-foreground mt-0.5">{r.neighborhood}</p>
                      <p className="text-xs text-muted-foreground">
                        {new Date(r.dateObserved).toLocaleDateString()} · {r.count} animal{r.count > 1 ? "s" : ""}
                      </p>
                    </div>
                    {selected?.id === r.id && (
                      <CheckCircle2 size={16} style={{ color: "#028391" }} className="flex-shrink-0 mt-0.5" />
                    )}
                  </div>
                </button>
              ))
            )}
          </div>

          {/* ── Right: generated report ── */}
          <div className="lg:col-span-3">
            {!selected ? (
              <div
                className="rounded-3xl p-10 text-center"
                style={{
                  background: "rgba(255,252,243,0.88)",
                  boxShadow: "0 2px 12px rgba(1,32,78,0.07)",
                }}
              >
                <div className="flex justify-center gap-4 mb-4 opacity-40">
                  <KurzgesagtCat size={60} />
                </div>
                <p className="text-muted-foreground text-sm">
                  Select a concern from the left to generate a report packet.
                </p>
              </div>
            ) : (
              <div
                className="rounded-3xl p-6"
                style={{
                  background: "rgba(255,252,243,0.94)",
                  boxShadow: "0 2px 12px rgba(1,32,78,0.07), 0 6px 24px rgba(1,32,78,0.06)",
                }}
              >
                {/* Action buttons */}
                <div className="flex flex-wrap gap-2 mb-5">
                  <button
                    data-testid="button-copy-report"
                    onClick={handleCopy}
                    className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-semibold transition-all"
                    style={{ background: "rgba(1,32,78,0.07)", border: "1px solid rgba(1,32,78,0.12)" }}
                  >
                    {copied ? <CheckCircle2 size={14} style={{ color: "#028391" }} /> : <Copy size={14} />}
                    {copied ? "Copied!" : "Copy Report"}
                  </button>
                  <button
                    data-testid="button-print-report"
                    onClick={() => window.print()}
                    className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-semibold transition-all"
                    style={{ background: "rgba(1,32,78,0.07)", border: "1px solid rgba(1,32,78,0.12)" }}
                  >
                    <Printer size={14} /> Print
                  </button>
                  <button
                    data-testid="button-download-report"
                    onClick={handleDownload}
                    className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-semibold text-white transition-all"
                    style={{ background: "#028391", boxShadow: "0 3px 10px rgba(2,131,145,0.3)" }}
                  >
                    <Download size={14} /> Download .txt
                  </button>
                </div>

                <pre
                  data-testid="text-generated-report"
                  className="text-xs font-mono leading-relaxed whitespace-pre-wrap overflow-auto max-h-[560px] rounded-2xl p-4"
                  style={{ background: "rgba(1,32,78,0.04)", color: "inherit" }}
                >
                  {reportText}
                </pre>
              </div>
            )}
          </div>
        </div>

        {/* ── Email templates ── */}
        {selected && (
          <div className="mt-8">
            <h3 className="font-heading font-bold text-base mb-4 flex items-center gap-2">
              <Copy size={15} style={{ color: "#028391" }} />
              Ready-to-Send Message Templates
            </h3>
            <div className="grid sm:grid-cols-3 gap-4">
              {EMAIL_TEMPLATES.map((tmpl) => {
                const text = tmpl.template(selected);
                const isCopied = copiedTmpl === tmpl.id;
                return (
                  <div
                    key={tmpl.id}
                    className="rounded-2xl p-5 flex flex-col gap-3"
                    style={{
                      background: "rgba(255,252,243,0.92)",
                      borderLeft: `4px solid ${tmpl.accent}`,
                      boxShadow: "0 2px 10px rgba(1,32,78,0.07)",
                    }}
                  >
                    <div
                      className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-bold self-start"
                      style={{ background: tmpl.light, color: tmpl.accent }}
                    >
                      {tmpl.title}
                    </div>
                    <p className="text-xs text-muted-foreground leading-relaxed flex-1">{text}</p>
                    <button
                      data-testid={`button-copy-${tmpl.id}`}
                      onClick={() => handleCopyTemplate(tmpl.id, text)}
                      className="w-full flex items-center justify-center gap-1.5 py-2 rounded-xl text-xs font-semibold transition-all"
                      style={
                        isCopied
                          ? { background: tmpl.accent, color: "#fff" }
                          : { background: tmpl.light, color: tmpl.accent, border: `1px solid ${tmpl.accent}33` }
                      }
                    >
                      {isCopied ? <CheckCircle2 size={12} /> : <Copy size={12} />}
                      {isCopied ? "Copied!" : "Copy Message"}
                    </button>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
